### route 404
GET http://localhost:3000/test

### findAll (auto status = "all", page=1 & limit=1_000)
GET http://localhost:3000/orders

### findAll with queries
GET http://localhost:3000/orders?status=pending&page=2&limit=100

### findUnique
GET http://localhost:3000/orders/500

### create
POST http://localhost:3000/orders
Content-Type: application/json

{
    "userId": 74,
    "products": [
        { "productId": 50, "price": 1016, "quantity": 1 },
        { "productId": 59, "price": 734, "quantity": 5 }
    ]
}


### patch status
PATCH http://localhost:3000/orders/1/status
Content-Type: application/json

{
    "status" : "cancelled"
}

### count all orders
GET http://localhost:3000/orders/count

### count pendind orders
GET http://localhost:3000/orders/count?status=pending